In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mtp

data = pd.read_csv("2018-2022(EN).csv")
data

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,PSA,WHH,WHD,WHA,VCH,VCD,VCA,PSCH,PSCD,PSCA
0,E0,10/8/2018,Man United,Leicester,2,1,H,1,0,H,...,7.50,1.57,3.8,6.00,1.57,4.0,7.00,1.55,4.07,7.69
1,E0,11/8/2018,Bournemouth,Cardiff,2,0,H,1,0,H,...,4.58,1.91,3.5,4.00,1.87,3.6,4.75,1.88,3.61,4.70
2,E0,11/8/2018,Fulham,Crystal Palace,0,2,A,0,1,A,...,3.00,2.45,3.3,2.80,2.50,3.4,3.00,2.62,3.38,2.90
3,E0,11/8/2018,Huddersfield,Chelsea,0,3,A,0,2,A,...,1.62,5.80,3.9,1.57,6.50,4.0,1.62,7.24,3.95,1.58
4,E0,11/8/2018,Newcastle,Tottenham,1,2,A,1,2,A,...,2.08,3.80,3.2,2.05,3.90,3.4,2.10,4.74,3.53,1.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,E0,22/5/2022,Crystal Palace,Man United,1,0,H,1,0,H,...,2.24,3.00,3.5,2.25,3.00,3.5,2.20,2.82,3.57,2.59
1516,E0,22/5/2022,Leicester,Southampton,4,1,H,0,0,D,...,3.91,1.88,3.8,3.75,1.83,3.8,3.80,1.70,4.39,4.67
1517,E0,22/5/2022,Liverpool,Wolves,3,1,H,1,1,D,...,21.36,1.15,7.0,19.00,1.13,8.0,19.00,1.14,9.75,19.00
1518,E0,22/5/2022,Man City,Aston Villa,3,2,H,0,1,A,...,20.27,1.15,7.0,19.00,1.13,7.5,18.00,1.17,8.40,17.00
1519,E0,22/5/2022,Norwich,Tottenham,0,5,A,0,2,A,...,1.27,10.00,6.0,1.25,11.50,6.0,1.22,9.82,5.51,1.34

In [2]:
def goal_difference(data, half_time_home_goals, half_time_away_goals, full_time_home_goals, full_time_away_goals):
    
    # Calculating Goal Difference in HALF TIME
    if (half_time_home_goals > half_time_away_goals):
        half_time_goal_difference = half_time_home_goals - half_time_away_goals
    elif (half_time_away_goals > half_time_home_goals):
        half_time_goal_difference = half_time_away_goals - half_time_home_goals
    else:
         half_time_goal_difference = half_time_home_goals - half_time_away_goals
            
    # Calculating Goal Difference in FULL TIME
    if (full_time_home_goals > full_time_away_goals):
        full_time_goal_difference = full_time_home_goals - full_time_away_goals
    elif (full_time_away_goals > full_time_home_goals):
        full_time_goal_difference = full_time_away_goals - full_time_home_goals
    else:
         full_time_goal_difference = full_time_home_goals - full_time_away_goals
            
            
    return half_time_goal_difference, full_time_goal_difference

In [3]:
htgd = []
ftgd = []
for index,row in data.iterrows():
    half_time_home_goals = row['HTHG']
    half_time_away_goals = row['HTAG']
    full_time_home_goals = row['FTHG']
    full_time_away_goals = row['FTAG']
    half_time_goal_difference, full_time_goal_difference = goal_difference(data, half_time_home_goals, half_time_away_goals, full_time_home_goals, full_time_away_goals)
    htgd.insert(index, half_time_goal_difference)
    ftgd.insert(index, full_time_goal_difference)
data['HTGD'] = htgd
data['FTGD'] = ftgd

In [4]:
#Feature Selection 

drop_cols1 = ['Div', 'Date']
newdf1 = data.drop(columns = drop_cols1)
input_dataset = newdf1.drop(newdf1.loc[:,'B365H':'PSCA'].columns, axis=1)
input_dataset

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,...,HF,AF,HC,AC,HY,AY,HR,AR,HTGD,FTGD
0,Man United,Leicester,2,1,H,1,0,H,A Marriner,8,...,11,8,2,5,2,1,0,0,1,1
1,Bournemouth,Cardiff,2,0,H,1,0,H,K Friend,12,...,11,9,7,4,1,1,0,0,1,2
2,Fulham,Crystal Palace,0,2,A,0,1,A,M Dean,15,...,9,11,5,5,1,2,0,0,1,2
3,Huddersfield,Chelsea,0,3,A,0,2,A,C Kavanagh,6,...,9,8,2,5,2,1,0,0,2,3
4,Newcastle,Tottenham,1,2,A,1,2,A,M Atkinson,15,...,11,12,3,5,2,2,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,Crystal Palace,Man United,1,0,H,1,0,H,M Atkinson,6,...,12,22,3,6,2,4,0,0,1,1
1516,Leicester,Southampton,4,1,H,0,0,D,J Moss,12,...,10,5,3,3,0,1,0,0,0,3
1517,Liverpool,Wolves,3,1,H,1,1,D,A Taylor,29,...,6,3,5,3,1,0,0,0,0,2
1518,Man City,Aston Villa,3,2,H,0,1,A,M Oliver,24,...,5,11,13,1,0,1,0,0,1,1
1519,Norwich,Tottenham,0,5,A,0,2,A,C Kavanagh,9,...,13,7,3,2,3,1,0,0,2,5

In [5]:
# Convert Categorical Variables to Numeric Variables [Home = 2, Draw = 1, Away = 0]

input_dataset["HomeTeam_code"] = input_dataset["HomeTeam"].astype("category").cat.codes
input_dataset["AwayTeam_code"] = input_dataset["AwayTeam"].astype("category").cat.codes
input_dataset["Referee_code"] = input_dataset["Referee"].astype("category").cat.codes
input_dataset["HTR_code"] = input_dataset["HTR"].astype("category").cat.codes
input_dataset["FTR_code"] = input_dataset["FTR"].astype("category").cat.codes

In [6]:
input_dataset

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,...,AY,HR,AR,HTGD,FTGD,HomeTeam_code,AwayTeam_code,Referee_code,HTR_code,FTR_code
0,Man United,Leicester,2,1,H,1,0,H,A Marriner,8,...,1,0,0,1,1,16,13,1,2,2
1,Bournemouth,Cardiff,2,0,H,1,0,H,K Friend,12,...,1,0,0,1,2,2,6,12,2,2
2,Fulham,Crystal Palace,0,2,A,0,1,A,M Dean,15,...,2,0,0,1,2,10,8,16,0,0
3,Huddersfield,Chelsea,0,3,A,0,2,A,C Kavanagh,6,...,1,0,0,2,3,11,7,4,0,0
4,Newcastle,Tottenham,1,2,A,1,2,A,M Atkinson,15,...,2,0,0,1,1,17,21,15,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,Crystal Palace,Man United,1,0,H,1,0,H,M Atkinson,6,...,4,0,0,1,1,8,16,15,2,2
1516,Leicester,Southampton,4,1,H,0,0,D,J Moss,12,...,1,0,0,0,3,13,20,11,1,2
1517,Liverpool,Wolves,3,1,H,1,1,D,A Taylor,29,...,0,0,0,0,2,14,25,3,1,2
1518,Man City,Aston Villa,3,2,H,0,1,A,M Oliver,24,...,1,0,0,1,1,15,1,17,0,2
1519,Norwich,Tottenham,0,5,A,0,2,A,C Kavanagh,9,...,1,0,0,2,5,18,21,4,0,0

In [7]:
drop_cols2 = ["HomeTeam", "AwayTeam", "Referee", "FTR", "HTR"]
preprocessed_dataset = input_dataset.drop(columns = drop_cols2)
preprocessed_dataset

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,...,AY,HR,AR,HTGD,FTGD,HomeTeam_code,AwayTeam_code,Referee_code,HTR_code,FTR_code
0,2,1,1,0,8,13,6,4,11,8,...,1,0,0,1,1,16,13,1,2,2
1,2,0,1,0,12,10,4,1,11,9,...,1,0,0,1,2,2,6,12,2,2
2,0,2,0,1,15,10,6,9,9,11,...,2,0,0,1,2,10,8,16,0,0
3,0,3,0,2,6,13,1,4,9,8,...,1,0,0,2,3,11,7,4,0,0
4,1,2,1,2,15,15,2,5,11,12,...,2,0,0,1,1,17,21,15,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515,1,0,1,0,6,10,3,4,12,22,...,4,0,0,1,1,8,16,15,2,2
1516,4,1,0,0,12,7,6,2,10,5,...,1,0,0,0,3,13,20,11,1,2
1517,3,1,1,1,29,7,8,5,6,3,...,0,0,0,0,2,14,25,3,1,2
1518,3,2,0,1,24,4,5,2,5,11,...,1,0,0,1,1,15,1,17,0,2
1519,0,5,0,2,9,19,0,13,13,7,...,1,0,0,2,5,18,21,4,0,0

In [8]:
#Extracting Independent and dependent Variable

X = preprocessed_dataset.drop(columns = ['FTR_code'])
y = preprocessed_dataset['FTR_code']

In [9]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.30, random_state=0)

In [10]:
# Feature Scaling  
from sklearn.preprocessing import StandardScaler

scaler_x= StandardScaler()    
x_train= scaler_x.fit_transform(X_train)    
x_test= scaler_x.transform(X_test)

In [11]:
#Using Random Forest Algorithm
from sklearn.ensemble import RandomForestClassifier  

model= RandomForestClassifier() # Create the model
model.fit(x_train, y_train) # Train the model
predictions = model.predict(x_test) # Making Predictions

In [12]:
#Calculating accuracy
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)
print(accuracy)

1.0

In [13]:
#Creating the Confusion matrix for Logistic Regression

from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, predictions)  
cm

array([[156,   0,   0],
       [  0,  99,   0],
       [  0,   0, 201]], dtype=int64)

In [14]:
# Making search space = give values to hyperparameters that you want to search in order to find the best set of values
search_space = {
    "n_estimators" : [90, 91, 92, 93, 94, 95],
    "max_depth" :[20, 22, 24, 26, 28, 30]
}

In [15]:
from sklearn.model_selection import GridSearchCV
#create the GridSearch object
GS = GridSearchCV(estimator = model,
                  param_grid = search_space,
                  scoring = ['accuracy', 'r2'],
                  refit = 'r2',
                  cv = 5,
                  verbose = 4)

In [16]:
GS.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV 1/5] END max_depth=20, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=20, n_estimators=90; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 3/5] END max_depth=20, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.2s
[CV 4/5] END max_depth=20, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=20, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=20, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=20, n_estimators=91; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 3/5] END max_depth=20, n_estimators=91; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=20, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=20, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=20, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=20, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 3/5] END max_depth=20, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=20, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=20, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=20, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=20, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 3/5] END max_depth=20, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=20, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=20, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=20, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=20, n_estimators=94; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=20, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=20, n_estimators=94; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=20, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=20, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=20, n_estimators=95; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=20, n_estimators=95; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 4/5] END max_depth=20, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=20, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=22, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=22, n_estimators=90; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=22, n_estimators=90; accuracy: (test=0.986) r2: (test=0.927) total time=   0.1s
[CV 4/5] END max_depth=22, n_estimators=90; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 5/5] END max_depth=22, n_estimators=90; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 1/5] END max_depth=22, n_estimators=91; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 2/5] END max_depth=22, n_estimators=91; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=22, n_estimators=91; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 4/5] END max_depth=22, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=22, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=22, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=22, n_estimators=92; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=22, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=22, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=22, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=22, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 2/5] END max_depth=22, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 3/5] END max_depth=22, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=22, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=22, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=22, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=22, n_estimators=94; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=22, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=22, n_estimators=94; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=22, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=22, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=22, n_estimators=95; accuracy: (test=0.986) r2: (test=0.927) total time=   0.1s
[CV 3/5] END max_depth=22, n_estimators=95; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=22, n_estimators=95; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=22, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=24, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=24, n_estimators=90; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=24, n_estimators=90; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 4/5] END max_depth=24, n_estimators=90; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=24, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=24, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=24, n_estimators=91; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=24, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=24, n_estimators=91; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=24, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=24, n_estimators=92; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 2/5] END max_depth=24, n_estimators=92; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=24, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=24, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=24, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=24, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 2/5] END max_depth=24, n_estimators=93; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=24, n_estimators=93; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 4/5] END max_depth=24, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s

[CV 5/5] END max_depth=24, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=24, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=24, n_estimators=94; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=24, n_estimators=94; accuracy: (test=0.986) r2: (test=0.927) total time=   0.1s
[CV 4/5] END max_depth=24, n_estimators=94; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=24, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=24, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=24, n_estimators=95; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=24, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=24, n_estimators=95; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=24, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=26, n_estimators=90; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 2/5] END max_depth=26, n_estimators=90; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 3/5] END max_depth=26, n_estimators=90; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=26, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=26, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=26, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=26, n_estimators=91; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=26, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=26, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=26, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=26, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=26, n_estimators=92; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=26, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=26, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=26, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=26, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 2/5] END max_depth=26, n_estimators=93; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=26, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=26, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=26, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=26, n_estimators=94; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 2/5] END max_depth=26, n_estimators=94; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=26, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=26, n_estimators=94; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=26, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=26, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=26, n_estimators=95; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=26, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=26, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=26, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.2s
[CV 1/5] END max_depth=28, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=28, n_estimators=90; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=28, n_estimators=90; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=28, n_estimators=90; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 5/5] END max_depth=28, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=28, n_estimators=91; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 2/5] END max_depth=28, n_estimators=91; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=28, n_estimators=91; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=28, n_estimators=91; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=28, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=28, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=28, n_estimators=92; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=28, n_estimators=92; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 4/5] END max_depth=28, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=28, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=28, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=28, n_estimators=93; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=28, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=28, n_estimators=93; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=28, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=28, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=28, n_estimators=94; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=28, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=28, n_estimators=94; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=28, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=28, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=28, n_estimators=95; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 3/5] END max_depth=28, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 4/5] END max_depth=28, n_estimators=95; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=28, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=30, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=30, n_estimators=90; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=30, n_estimators=90; accuracy: (test=0.986) r2: (test=0.927) total time=   0.1s
[CV 4/5] END max_depth=30, n_estimators=90; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=30, n_estimators=90; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=30, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=30, n_estimators=91; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 3/5] END max_depth=30, n_estimators=91; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 4/5] END max_depth=30, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=30, n_estimators=91; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s

[CV 1/5] END max_depth=30, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 2/5] END max_depth=30, n_estimators=92; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=30, n_estimators=92; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 4/5] END max_depth=30, n_estimators=92; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=30, n_estimators=92; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=30, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=30, n_estimators=93; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=30, n_estimators=93; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 4/5] END max_depth=30, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 5/5] END max_depth=30, n_estimators=93; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=30, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 2/5] END max_depth=30, n_estimators=94; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=30, n_estimators=94; accuracy: (test=0.986) r2: (test=0.927) total time=   0.1s
[CV 4/5] END max_depth=30, n_estimators=94; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=30, n_estimators=94; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s
[CV 1/5] END max_depth=30, n_estimators=95; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 2/5] END max_depth=30, n_estimators=95; accuracy: (test=0.991) r2: (test=0.951) total time=   0.1s
[CV 3/5] END max_depth=30, n_estimators=95; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 4/5] END max_depth=30, n_estimators=95; accuracy: (test=0.995) r2: (test=0.976) total time=   0.1s
[CV 5/5] END max_depth=30, n_estimators=95; accuracy: (test=1.000) r2: (test=1.000) total time=   0.1s

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [20, 22, 24, 26, 28, 30],
                         'n_estimators': [90, 91, 92, 93, 94, 95]},
             refit='r2', scoring=['accuracy', 'r2'], verbose=4)

In [17]:
print("Best Hyperparameters: ", GS.best_params_) # take the best model with the details that we searched for
print("Best Scores: ", GS.best_score_) # take the R^2 score of best model

Best Hyperparameters:  {'max_depth': 20, 'n_estimators': 90}
Best Scores:  0.9951361534509335